import React, { useState } from 'react';
import { fmt, calcMonths, calcInterest, calcSettlement, calcPayout } from '../utils/calculations';

export default function Calculator() {
  // Mode 1
  const [p1, setP1] = useState({ amount: '', rate: '2', deduct: false });
  // Mode 2
  const [p2, setP2] = useState({ amount: '', rate: '2', pawnDate: '', closeDate: new Date().toISOString().split('T')[0], paidMonths: '0' });
  const [tab, setTab] = useState(1);

  // Payout calcs
  const payout = p1.amount && p1.rate
    ? calcPayout(+p1.amount, +p1.rate, p1.deduct)
    : { interest: 0, payout: 0 };

  // Settlement calcs
  const months = p2.pawnDate && p2.closeDate
    ? calcMonths(p2.pawnDate, p2.closeDate) : 0;
  const settlement = p2.amount && p2.rate
    ? calcSettlement(+p2.amount, +p2.rate, months, +p2.paidMonths || 0)
    : { pending: 0, interest: 0, total: 0 };

  const printPayout = () => {
    const now = new Date().toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'short' });
    const w = window.open('', '_blank', 'width=520,height=600');
    w.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>Payout Receipt</title>
    <style>body{font-family:'Segoe UI',sans-serif;padding:36px 40px;max-width:480px;margin:0 auto;color:#111}
    .hd{text-align:center;border-bottom:2px solid #111;padding-bottom:14px;margin-bottom:20px}
    .hd h1{font-size:1.4rem;font-weight:900}.hd p{font-size:.78rem;color:#666}
    table{width:100%;border-collapse:collapse;margin-bottom:10px}
    td{padding:9px 4px;border-bottom:1px solid #eee;font-size:.9rem}.a{text-align:right;font-weight:700}
    .big{background:#dcfce7;border:2px solid #86efac;border-radius:10px;padding:14px 18px;display:flex;justify-content:space-between;font-size:1.2rem;font-weight:900;color:#15803d;margin-top:8px}
    .footer{margin-top:20px;text-align:center;font-size:.72rem;color:#aaa;border-top:1px solid #eee;padding-top:12px}
    .btn{display:block;margin:14px auto 0;padding:10px 26px;background:#111;color:#fff;border:none;border-radius:8px;font-weight:700;cursor:pointer}
    @media print{.btn{display:none}}</style></head><body>
    <div class="hd"><h1>⚖️ PawnCalc</h1><p>Customer Payout Receipt &mdash; ${now}</p></div>
    <table>
      <tr><td>Loan Amount</td><td class="a">${fmt(+p1.amount)}</td></tr>
      <tr><td>Interest Rate</td><td class="a">${p1.rate}% per month</td></tr>
      ${p1.deduct ? `<tr><td>Advance Interest Deducted (1st Month)</td><td class="a" style="color:#dc2626">− ${fmt(payout.interest)}</td></tr>` : ''}
    </table>
    <div class="big"><span>💵 Amount Given to Customer</span><span>${fmt(payout.payout)}</span></div>
    <div class="footer">Generated by PawnCalc</div>
    <button class="btn" onclick="window.print()">🖨️ Print</button>
    </body></html>`);
    w.document.close();
  };

  const printSettlement = () => {
    const now = new Date().toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'short' });
    const w = window.open('', '_blank', 'width=520,height=650');
    w.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>Settlement Receipt</title>
    <style>body{font-family:'Segoe UI',sans-serif;padding:36px 40px;max-width:480px;margin:0 auto;color:#111}
    .hd{text-align:center;border-bottom:2px solid #111;padding-bottom:14px;margin-bottom:20px}
    .hd h1{font-size:1.4rem;font-weight:900}.hd p{font-size:.78rem;color:#666}
    table{width:100%;border-collapse:collapse;margin-bottom:10px}
    td{padding:9px 4px;border-bottom:1px solid #eee;font-size:.9rem}.a{text-align:right;font-weight:700}
    .big{background:#dbeafe;border:2px solid #93c5fd;border-radius:10px;padding:14px 18px;display:flex;justify-content:space-between;font-size:1.2rem;font-weight:900;color:#1d4ed8;margin-top:8px}
    .footer{margin-top:20px;text-align:center;font-size:.72rem;color:#aaa;border-top:1px solid #eee;padding-top:12px}
    .btn{display:block;margin:14px auto 0;padding:10px 26px;background:#111;color:#fff;border:none;border-radius:8px;font-weight:700;cursor:pointer}
    @media print{.btn{display:none}}</style></head><body>
    <div class="hd"><h1>⚖️ PawnCalc</h1><p>Loan Closing Settlement &mdash; ${now}</p></div>
    <table>
      <tr><td>Loan Principal</td><td class="a">${fmt(+p2.amount)}</td></tr>
      <tr><td>Interest Rate</td><td class="a">${p2.rate}% per month</td></tr>
      <tr><td>Total Loan Months</td><td class="a">${months}</td></tr>
      <tr><td>✅ Interest Already Paid</td><td class="a" style="color:#15803d">${p2.paidMonths} months</td></tr>
      <tr><td>⌛ Remaining Months</td><td class="a">${settlement.pending}</td></tr>
      <tr><td>📈 Pending Interest</td><td class="a" style="color:#dc2626">${fmt(settlement.interest)}</td></tr>
    </table>
    <div class="big"><span>💰 Final Closing Amount</span><span>${fmt(settlement.total)}</span></div>
    <div class="footer">Generated by PawnCalc</div>
    <button class="btn" onclick="window.print()">🖨️ Print</button>
    </body></html>`);
    w.document.close();
  };

  return (
    <div className="max-w-4xl space-y-5">
      <div>
        <h1 className="text-2xl font-black text-slate-800 dark:text-white">🧮 Interest Calculator</h1>
        <p className="text-slate-500 text-sm">Real-time pawn broker calculations</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2">
        {[[1,'💵 Customer Payout'],[2,'🔒 Loan Settlement']].map(([n,label]) => (
          <button key={n} onClick={() => setTab(n)}
            className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all
              ${tab === n ? 'bg-gold-500 text-white' : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:border-gold-500'}`}>
            {label}
          </button>
        ))}
      </div>

      {tab === 1 && (
        <div className="grid lg:grid-cols-2 gap-5">
          <div className="card p-5 space-y-4">
            <h2 className="font-bold text-slate-700 dark:text-slate-200">💵 Customer Payout Calculation</h2>
            <div>
              <label className="label">Loan Amount (₹)</label>
              <input type="number" inputMode="numeric" className="input" placeholder="50000" value={p1.amount} onChange={e => setP1(f => ({ ...f, amount: e.target.value }))} />
            </div>
            <div>
              <label className="label">Interest Rate (% / month)</label>
              <input type="number" inputMode="decimal" className="input" placeholder="2" step="0.1" value={p1.rate} onChange={e => setP1(f => ({ ...f, rate: e.target.value }))} />
            </div>
            <label className="flex items-center justify-between gap-3 p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl cursor-pointer hover:border-gold-500 transition-all">
              <span className="text-sm font-semibold">☑ Deduct First Month Interest Before Giving Loan</span>
              <div className="relative flex-shrink-0">
                <input type="checkbox" className="sr-only" checked={p1.deduct} onChange={e => setP1(f => ({ ...f, deduct: e.target.checked }))} />
                <div className={`w-10 h-5 rounded-full transition-colors ${p1.deduct ? 'bg-gold-500' : 'bg-slate-300 dark:bg-slate-600'}`}>
                  <div className={`w-4 h-4 bg-white rounded-full shadow mt-0.5 mx-0.5 transition-transform ${p1.deduct ? 'translate-x-5' : ''}`} />
                </div>
              </div>
            </label>
            <button onClick={printPayout} disabled={!p1.amount} className="btn-outline w-full">🖨️ Print Receipt</button>
          </div>

          <div className="space-y-3">
            <div className="card p-4 flex justify-between items-center border-amber-200 dark:border-amber-900 bg-amber-50/50 dark:bg-amber-950/20">
              <span className="text-sm font-bold text-amber-700 dark:text-amber-400 uppercase">🏦 Total Loan Amount</span>
              <span className="text-xl font-black text-amber-700 dark:text-amber-400">{fmt(+p1.amount || 0)}</span>
            </div>
            {p1.deduct && (
              <div className="card p-4 flex justify-between items-center border-red-200 dark:border-red-900 bg-red-50/50 dark:bg-red-950/20">
                <span className="text-sm font-bold text-red-600 dark:text-red-400 uppercase">📉 Advance Interest Deducted</span>
                <span className="text-xl font-black text-red-600 dark:text-red-400">−{fmt(payout.interest)}</span>
              </div>
            )}
            <div className="card p-6 flex justify-between items-center border-emerald-200 dark:border-emerald-900 bg-emerald-50/50 dark:bg-emerald-950/20">
              <span className="text-sm font-black text-emerald-700 dark:text-emerald-400 uppercase">💵 Amount Given To Customer</span>
              <span className="text-3xl font-black text-emerald-700 dark:text-emerald-400">{fmt(payout.payout)}</span>
            </div>
          </div>
        </div>
      )}

      {tab === 2 && (
        <div className="grid lg:grid-cols-2 gap-5">
          <div className="card p-5 space-y-4">
            <h2 className="font-bold text-slate-700 dark:text-slate-200">🔒 Loan Closing Settlement</h2>
            <div className="grid sm:grid-cols-2 gap-3">
              <div>
                <label className="label">Loan Amount (₹)</label>
                <input type="number" inputMode="numeric" className="input" placeholder="50000" value={p2.amount} onChange={e => setP2(f => ({ ...f, amount: e.target.value }))} />
              </div>
              <div>
                <label className="label">Interest Rate (% / mo)</label>
                <input type="number" inputMode="decimal" className="input" placeholder="2" step="0.1" value={p2.rate} onChange={e => setP2(f => ({ ...f, rate: e.target.value }))} />
              </div>
              <div>
                <label className="label">Pawn Date</label>
                <input type="date" className="input" value={p2.pawnDate} onChange={e => setP2(f => ({ ...f, pawnDate: e.target.value }))} />
              </div>
              <div>
                <label className="label">Closing Date</label>
                <input type="date" className="input" value={p2.closeDate} onChange={e => setP2(f => ({ ...f, closeDate: e.target.value }))} />
              </div>
              <div className="sm:col-span-2">
                <label className="label">✅ Interest Months Already Paid</label>
                <input type="number" inputMode="numeric" pattern="[0-9]*" className="input" min="0" value={p2.paidMonths} onChange={e => setP2(f => ({ ...f, paidMonths: e.target.value }))} />
              </div>
            </div>
            <button onClick={printSettlement} disabled={!p2.amount || !p2.pawnDate} className="btn-outline w-full">🖨️ Print Settlement Receipt</button>
          </div>

          <div className="space-y-3">
            {[
              ['📆 Total Loan Months', `${months} Months`, 'slate'],
              ['✅ Already Paid', `${p2.paidMonths || 0} Months`, 'emerald'],
              ['⌛ Remaining Months', `${settlement.pending} Months`, 'amber'],
              ['📈 Pending Interest', fmt(settlement.interest), 'red'],
              ['🏦 Loan Principal', fmt(+p2.amount || 0), 'gold'],
            ].map(([label, val, c]) => (
              <div key={label} className={`card p-4 flex justify-between items-center
                ${c === 'emerald' ? 'border-emerald-200 dark:border-emerald-900 bg-emerald-50/50 dark:bg-emerald-950/20' :
                  c === 'amber'   ? 'border-amber-200 dark:border-amber-900 bg-amber-50/50 dark:bg-amber-950/20' :
                  c === 'red'     ? 'border-red-200 dark:border-red-900 bg-red-50/50 dark:bg-red-950/20' :
                  c === 'gold'    ? 'border-amber-200 dark:border-amber-900' : ''}`}>
                <span className={`text-xs font-bold uppercase tracking-wider
                  ${c === 'emerald' ? 'text-emerald-600 dark:text-emerald-400' :
                    c === 'amber'   ? 'text-amber-600 dark:text-amber-400' :
                    c === 'red'     ? 'text-red-600 dark:text-red-400' :
                    c === 'gold'    ? 'text-amber-600 dark:text-amber-400' :
                    'text-slate-500'}`}>{label}</span>
                <span className={`text-lg font-black
                  ${c === 'emerald' ? 'text-emerald-700 dark:text-emerald-400' :
                    c === 'amber'   ? 'text-amber-700 dark:text-amber-400' :
                    c === 'red'     ? 'text-red-600 dark:text-red-400' :
                    c === 'gold'    ? 'text-amber-600 dark:text-amber-400' :
                    ''}`}>{val}</span>
              </div>
            ))}
            <div className="card p-6 flex justify-between items-center border-blue-200 dark:border-blue-900 bg-blue-50/50 dark:bg-blue-950/20">
              <span className="text-sm font-black text-blue-700 dark:text-blue-400 uppercase">💰 Final Closing Amount</span>
              <span className="text-3xl font-black text-blue-700 dark:text-blue-400">{fmt(settlement.total)}</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
