import { fmt, fmtDate, calcMonths } from './calculations';
import { brand } from '../config/brand';

export function printLoanReceipt(loan) {
  const win = window.open('', '_blank', 'width=620,height=800');
  const c = loan.customer;
  const html = `<!DOCTYPE html><html><head>
    <meta charset="UTF-8"/>
    <title>Loan Receipt — ${loan.loanNumber}</title>
    <style>
      *{box-sizing:border-box;margin:0;padding:0}
      body{font-family:'Segoe UI',sans-serif;padding:36px 40px;color:#111;max-width:580px;margin:0 auto}
      .hd{text-align:center;border-bottom:2px solid #111;padding-bottom:14px;margin-bottom:20px}
      .hd h1{font-size:1.4rem;font-weight:900}
      .hd p{font-size:.78rem;color:#666}
      .badge{display:inline-block;padding:2px 10px;border-radius:999px;font-size:.7rem;font-weight:700;
             background:${loan.status==='active'?'#dcfce7':'#f1f5f9'};
             color:${loan.status==='active'?'#15803d':'#475569'};
             border:1px solid ${loan.status==='active'?'#86efac':'#cbd5e1'}}
      .grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 20px;margin-bottom:16px}
      .row{padding:4px 0;border-bottom:1px solid #f1f5f9}
      .lbl{font-size:.72rem;color:#888;text-transform:uppercase;letter-spacing:.4px}
      .val{font-size:.92rem;font-weight:700}
      .big{background:#f8fafc;border:2px solid #e2e8f0;border-radius:12px;padding:14px 18px;margin:12px 0;display:flex;justify-content:space-between;align-items:center}
      .big.green{background:#dcfce7;border-color:#86efac}
      .big .label{font-size:.75rem;font-weight:700;text-transform:uppercase;color:#64748b}
      .big .amount{font-size:1.4rem;font-weight:900;color:#15803d}
      .payments{margin-top:14px}
      .payments h3{font-size:.85rem;font-weight:700;margin-bottom:8px;color:#475569}
      table{width:100%;border-collapse:collapse;font-size:.82rem}
      th{background:#f8fafc;padding:7px 10px;text-align:left;font-size:.7rem;text-transform:uppercase;color:#888}
      td{padding:7px 10px;border-bottom:1px solid #f1f5f9}
      .footer{margin-top:20px;text-align:center;font-size:.72rem;color:#aaa;border-top:1px solid #e2e8f0;padding-top:12px}
      .btn{display:block;margin:16px auto 0;padding:10px 28px;background:#111;color:#fff;border:none;border-radius:8px;font-weight:700;cursor:pointer;font-size:.88rem}
      @media print{.btn{display:none}}
    </style>
  </head><body>
    <div class="hd">
      <h1>${brand.name}</h1>
      <p>${brand.tagline} — Pawn Broker Finance Management</p>
      <p style="margin-top:6px"><strong>${loan.loanNumber}</strong> &nbsp; <span class="badge">${loan.status.toUpperCase()}</span></p>
    </div>
    <div class="grid">
      <div class="row"><div class="lbl">Customer</div><div class="val">${c?.name||'—'}</div></div>
      <div class="row"><div class="lbl">Phone</div><div class="val">${c?.phone||'—'}</div></div>
      <div class="row"><div class="lbl">Item</div><div class="val">${loan.itemDescription}</div></div>
      <div class="row"><div class="lbl">Weight</div><div class="val">${loan.itemWeight||'—'}</div></div>
      <div class="row"><div class="lbl">Pawn Date</div><div class="val">${fmtDate(loan.pawnDate)}</div></div>
      <div class="row"><div class="lbl">Interest Rate</div><div class="val">${loan.interestRate}% / month</div></div>
      <div class="row"><div class="lbl">Loan Amount</div><div class="val">${fmt(loan.principalAmount)}</div></div>
      <div class="row"><div class="lbl">Advance Deducted</div><div class="val">${loan.advanceInterestDeducted?fmt(loan.advanceInterestAmount):'None'}</div></div>
    </div>
    <div class="big green">
      <div><div class="label">Amount Given to Customer</div></div>
      <div class="amount">${fmt(loan.amountGivenToCustomer||loan.principalAmount)}</div>
    </div>
    ${loan.payments?.length ? `
    <div class="payments">
      <h3>Interest Payment History</h3>
      <table><thead><tr><th>Date</th><th>Months</th><th>Amount</th><th>Notes</th></tr></thead><tbody>
        ${loan.payments.map(p=>`<tr><td>${fmtDate(p.paidDate)}</td><td>${p.months}</td><td>${fmt(p.amount)}</td><td>${p.notes||'—'}</td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}
    ${loan.status==='closed' ? `
    <div class="big" style="background:#eff6ff;border-color:#93c5fd;margin-top:12px">
      <div><div class="label" style="color:#64748b">Closing Amount</div></div>
      <div class="amount" style="color:#1d4ed8">${fmt(loan.closingAmount)}</div>
    </div>` : ''}
    <div class="footer">Generated by ${brand.name} &mdash; ${new Date().toLocaleString('en-IN')}</div>
    <button class="btn" onclick="window.print()">🖨️ Print</button>
  </body></html>`;
  win.document.write(html);
  win.document.close();
}

export function printReport(loans, summary, filters) {
  const win = window.open('', '_blank', 'width=900,height=700');
  const html = `<!DOCTYPE html><html><head>
    <meta charset="UTF-8"/><title>PawnCalc Report</title>
    <style>
      *{box-sizing:border-box;margin:0;padding:0}
      body{font-family:'Segoe UI',sans-serif;padding:30px 36px;color:#111}
      h1{font-size:1.3rem;font-weight:900;margin-bottom:4px}
      .sub{font-size:.8rem;color:#666;margin-bottom:20px}
      .stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}
      .stat{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px 14px}
      .stat .l{font-size:.7rem;text-transform:uppercase;color:#888;margin-bottom:4px}
      .stat .v{font-size:1.2rem;font-weight:800}
      table{width:100%;border-collapse:collapse;font-size:.8rem}
      th{background:#f1f5f9;padding:8px 10px;text-align:left;font-size:.68rem;text-transform:uppercase;color:#64748b}
      td{padding:7px 10px;border-bottom:1px solid #f1f5f9}
      .btn{margin-top:16px;padding:10px 26px;background:#111;color:#fff;border:none;border-radius:8px;font-weight:700;cursor:pointer}
      @media print{.btn{display:none}}
    </style>
  </head><body>
    <h1>${brand.name} — Loan Report</h1>
    <div class="sub">Generated: ${new Date().toLocaleString('en-IN')} &nbsp;|&nbsp; Period: ${filters||'All Time'}</div>
    <div class="stats">
      <div class="stat"><div class="l">Total Loans</div><div class="v">${summary.totalLoans}</div></div>
      <div class="stat"><div class="l">Total Principal</div><div class="v">${fmt(summary.totalPrincipal)}</div></div>
      <div class="stat"><div class="l">Active</div><div class="v">${summary.totalActive}</div></div>
      <div class="stat"><div class="l">Recovered</div><div class="v">${fmt(summary.totalRecovered)}</div></div>
    </div>
    <table><thead><tr><th>Loan #</th><th>Customer</th><th>Item</th><th>Principal</th><th>Rate</th><th>Pawn Date</th><th>Status</th><th>Closing</th></tr></thead>
    <tbody>
      ${loans.map(l=>`<tr>
        <td>${l.loanNumber}</td>
        <td>${l.customer?.name||'—'}</td>
        <td>${l.itemDescription}</td>
        <td>${fmt(l.principalAmount)}</td>
        <td>${l.interestRate}%</td>
        <td>${fmtDate(l.pawnDate)}</td>
        <td>${l.status}</td>
        <td>${l.closingAmount?fmt(l.closingAmount):'—'}</td>
      </tr>`).join('')}
    </tbody></table>
    <button class="btn" onclick="window.print()">🖨️ Print Report</button>
  </body></html>`;
  win.document.write(html);
  win.document.close();
}
